zuul:
  routes:
#     myProduct:
#       path: /myProduct/**
#       serviceId: product
      #简洁写法 路由映射关系
      product: /yxm/**
  #配置不允许访问的路由
  ignored-patterns:
    - /**/product/list      
      
spring:
  rabbitmq:
    host: 192.168.1.143
    port: 5672
    username: guest
    password: guest
      
