zuul:
  routes:
#     myProduct:
#       path: /myProduct/**
#       serviceId: product
      #设置敏感头信息  为空所有头信息都不拦截 不设置默认会拦截cookie
#       sensitiveHeaders:
      #简洁写法 路由映射关系
      product: /yxm/**
  #配置不允许访问的路由
#   ignored-patterns:
#     - /**/product/list      
# 设置全局的敏感头配置 为空头信息都不拦  
  sensitive-headers:      
spring:
  rabbitmq:
    host: 192.168.1.143
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.1.143
    port: 6379    
      
