zuul:
  routes:
#     myProduct:
#       path: /myProduct/**
#       serviceId: product
      #简洁写法
      product: /yxm/**
      
spring:
  rabbitmq:
    host: 192.168.1.143
    port: 5672
    username: guest
    password: guest
      
