spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.143:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  redis:
    host: 192.168.1.143
    port: 6379    
  rabbitmq:
    host: 192.168.1.143
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
